sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - /^greenkeeper-.*$/
notifications:
  email: false
node_js:
  - 'node'
  - 'lts/*'
after_success: npm run coverage
